version: '3.8'

services:
  # 1. SERVICIO DE BASE DE DATOS
  db:
    image: postgres:15-alpine
    container_name: postgres-clientes
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      # Guarda los datos en un volumen persistente para no perderlos si se apaga el contenedor
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. SERVICIO DE LA API EN GO
  api:
    build: . # Le dice que busque el Dockerfile en esta misma carpeta y lo compile
    container_name: api-clientes-go
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      # ¡ATENCIÓN JUNIOR! Aquí ocurre la magia de Docker.
      # Ya no usamos "localhost". Usamos el nombre del servicio ("db")
      # Docker tiene un DNS interno que resuelve "db" a la IP del contenedor de Postgres.
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      API_KEY: ${API_KEY}
      SSL_ENABLED: ${SSL_ENABLED}
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
      APP_HOST: ${APP_HOST}
      SSL_PORT: ${SSL_PORT}
    volumes:
      # Montamos el directorio de certificados SSL en el contenedor
      - ./certs/cert.crt:/app/certs/cert.crt:ro
      - ./certs/private.key:/app/certs/private.key:ro
    depends_on:
      - db # Espera a que el contenedor 'db' se inicie antes de levantar la API
    restart: unless-stopped

# Declaramos el volumen que usamos en el servicio de la base de datos
volumes:
  pg_data: