version: '3.8'

services:
  # 1. SERVICIO DE BASE DE DATOS
  db:
    image: postgres:15-alpine
    container_name: postgres-clientes
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: secreto
      POSTGRES_DB: clientes_db
    ports:
      - "5436:5432"
    volumes:
      # Guarda los datos en un volumen persistente para no perderlos si se apaga el contenedor
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. SERVICIO DE LA API EN GO
  api:
    build: . # Le dice que busque el Dockerfile en esta misma carpeta y lo compile
    container_name: api-clientes-go
    ports:
      - "8080:8080"
    environment:
      # ¡ATENCIÓN JUNIOR! Aquí ocurre la magia de Docker.
      # Ya no usamos "localhost". Usamos el nombre del servicio ("db")
      # Docker tiene un DNS interno que resuelve "db" a la IP del contenedor de Postgres.
      DB_HOST: db
      DB_USER: usuario
      DB_PASSWORD: secreto
      DB_NAME: clientes_db
      DB_PORT: 5432
      API_KEY: secreto123
    depends_on:
      - db # Espera a que el contenedor 'db' se inicie antes de levantar la API
    restart: unless-stopped

# Declaramos el volumen que usamos en el servicio de la base de datos
volumes:
  pg_data: